server:
  port: 8765

info:
  component: Edge Server

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 10000
        requestVolumeThreshold: 3
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

health:
  config:
    enabled: false

# enable all actuator endpoints - tremendously useful for troubleshooting properties, mappings, etc. of running services
management:
  endpoints:
    web:
      exposure:
        include: '*'


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"

  ribbon:
    eager-load:
      enabled: true

  retryable: true

  prefix: /api/v1

  routes:
    demo-service:
      path: /demo-app/**
      sensitiveHeaders:

